/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Assignees_GetAssignees"];
        put: operations["Assignees_UpsertBrandSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Assignees_GetAssigneeById"];
        put?: never;
        post?: never;
        delete: operations["Assignees_DeleteAssigneeById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Authorization_Exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Authorization_UserinfoGET"];
        put?: never;
        post: operations["Authorization_UserinfoPOST"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brandsettings/by-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandSettings_GetBrandSettingByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brandsettings/by-owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandSettings_GetBrandSettingByOwnerId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brandsettings/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BrandSettings_UpsertBrandSetting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Contacts_CreateContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/by-group/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Exams_GetExamsByGroupExamId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/generate-exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Exams_GenerateExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/full-critical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Exams_GenerationExamFullCritical"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Exams_GenerationExamFull"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/generate-random-exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Exams_GenerateExam2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examsubmissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExamSubmissions_GetExamSubmissionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examsubmissions/start-exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExamSubmissions_StartExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examsubmissions/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExamSubmissions_SubmitExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feetypes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeeTypes_GetFeeTypes"];
        put: operations["FeeTypes_UpsertFeeType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feetypes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeeTypes_GetFeeTypeById"];
        put?: never;
        post?: never;
        delete: operations["FeeTypes_DeleteFeeTypeById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group-exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GroupExams_GetAllGroupExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/license-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LicenseTypes_GetAllLicenseTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/recognition/citizen-by-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Persons_RecognizeCitizenByFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Persons_ExportCitizenInfoToPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/by-exam/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Questions_GetExamsByGroupExamId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Questions_ExportCitizenInfoToPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/change-url-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Questions_ChangeQuestionImageUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Questions_GetQuestionDetailById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registration-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistrationRecords_GetRegistrationRecordsWithPagination"];
        put?: never;
        post: operations["RegistrationRecords_CreateRegistrationRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registration-records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["RegistrationRecords_UpdateRegistrationRecord"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Samples_GetSecretResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Uploads_UploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Uploads_UploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_GetUserInfoByReferenceToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Users_Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicle-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VehicleTypes_GetAllLicenseTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedListOfAssigneeDto: {
            data?: components["schemas"]["AssigneeDto"][];

            /** Format: int32 */
            pageNumber?: number;

            /** Format: int32 */
            totalPages?: number;

            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        AssigneeDto: {
            id?: string;
            fullName?: string;
            phone?: string;
            description?: string;
            active?: boolean;
            assigneeType?: components["schemas"]["AssigneeType"];
        };

        /** @enum {integer} */
        AssigneeType: 1 | 2 | 3;
        BaseResponseOfAssigneeDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["AssigneeDto"] | null;
        };
        BaseResponse: {
            success?: boolean;
            message?: string | null;
            statusCode?: components["schemas"]["HttpStatusCode"];
        };

        /** @enum {integer} */
        HttpStatusCode: 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 300 | 301 | 301 | 302 | 302 | 303 | 303 | 304 | 305 | 306 | 307 | 307 | 308 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 421 | 422 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 510 | 511;
        BaseResponseOfBoolean: components["schemas"]["BaseResponse"] & {
            data?: boolean;
        };
        UpsertAssigneeCommand: {
            id?: string | null;
            fullName?: string;
            phone?: string;
            description?: string;
            active?: boolean;
            assigneeType?: components["schemas"]["AssigneeType"];
        };
        BaseResponseOfBrandSettingDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["BrandSettingDto"] | null;
        };
        BrandSettingDto: {
            avatarUrl?: string;
            name?: string;
            shortDescription?: string | null;
            description?: string | null;
            email?: string | null;
            phoneNumber?: string | null;
            address?: string | null;
            images?: string[] | null;
        };
        UpsertBrandSettingCommand: {
            avatarUrl?: string;
            name?: string;
            shortDescription?: string | null;
            description?: string | null;
            email?: string | null;
            phoneNumber?: string | null;
            address?: string | null;
            images?: string[] | null;
        };
        CreateContactCommand: {
            fullName?: string;
            email?: string;
            message?: string;
        };
        BaseResponseOfListOfExamDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["ExamDto"][] | null;
        };
        ExamDto: {
            id?: string;
            name?: string;
            description?: string;

            /** Format: int32 */
            totalQuestions?: number;

            /** Format: int32 */
            passingScore?: number;

            /** Format: int32 */
            durationMinutes?: number;

            /** Format: int32 */
            order?: number;
            examType?: components["schemas"]["ExamType"];
            groupExamType?: components["schemas"]["GroupExamType"] | null;
            licenseTypeCode?: string;
            groupExamId?: string;
        };

        /** @enum {integer} */
        ExamType: 1 | 2;

        /** @enum {integer} */
        GroupExamType: 0 | 1 | 2;
        GenerateExamsCommand: {
            groupExamId?: string;
            licenseTypeCode?: string;
            questionNumbers?: number[];
            criticalQuestionNumbers?: number[];

            /** Format: int32 */
            numberOfExams?: number;

            /** Format: int32 */
            questionsPerExam?: number;

            /** Format: int32 */
            criticalQuestionsPerExam?: number;

            /** Format: int32 */
            durationMinutes?: number;

            /** Format: int32 */
            passingScore?: number;
        };
        GenerationExamFullCriticalCommand: {
            groupExamId?: string;
            licenseTypeCode?: string;
            criticalQuestionNumbers?: number[];
        };
        GenerationExamFullCommand: {
            groupExamId?: string;
            licenseTypeCode?: string;
            questionNumbers?: number[];
            criticalQuestionNumbers?: number[];
        };
        BaseResponseOfExamDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["ExamDto"] | null;
        };
        GenerateRandomExamsCommand: {
            groupExamId?: string;
            licenseTypeCode?: string;
        };
        BaseResponseOfExamSubmissionResultDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["ExamSubmissionResultDto"] | null;
        };
        ExamSubmissionResultDto: {
            id?: string;
            licenseTypeDto?: components["schemas"]["LicenseTypeDto"];

            /** Format: duration */
            duration?: string;

            /** Format: int32 */
            totalQuestions?: number;

            /** Format: int32 */
            correctAnswerCount?: number;
            hasCriticalMistake?: boolean;
            isPassed?: boolean;
            groupExamType?: components["schemas"]["GroupExamType"];
            exam?: components["schemas"]["ExamDto"];
            userAnswers?: components["schemas"]["ExamSubmissionAnswerDto"][];
        };
        LicenseTypeDto: {
            code?: string;
            name?: string;
            description?: string;
        };
        ExamSubmissionAnswerDto: {
            selectedAnswerId?: string | null;
            question?: components["schemas"]["SubmitQuestionDto"];
        };
        SubmitQuestionDto: {
            id?: string;
            explanation?: string | null;

            /** Format: int32 */
            order?: number;
            content?: string;
            imageUrl?: string | null;
            isCriticalQuestion?: boolean;
            answers?: components["schemas"]["SubmitAnswerDto"][];
        };
        SubmitAnswerDto: {
            id?: string;

            /** Format: int32 */
            order?: number;
            isCorrect?: boolean;
            content?: string;
        };
        BaseResponseOfCreateExamSubmissionResultDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["CreateExamSubmissionResultDto"] | null;
        };
        CreateExamSubmissionResultDto: {
            examSubmissionId?: string;
        };
        CreateExamSubmissionCommand: {
            examId?: string;
        };
        SubmitExamCommand: {
            examSubmissionId?: string;
            answers?: components["schemas"]["AnswerSubmissionRequestDto"][];
        };
        AnswerSubmissionRequestDto: {
            questionId?: string;
            selectedAnswerId?: string | null;
        };
        PaginatedListOfFeeTypeDto: {
            data?: components["schemas"]["FeeTypeDto"][];

            /** Format: int32 */
            pageNumber?: number;

            /** Format: int32 */
            totalPages?: number;

            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        FeeTypeDto: {
            id?: string;
            name?: string;
            description?: string;
            active?: boolean;
        };
        BaseResponseOfFeeTypeDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["FeeTypeDto"] | null;
        };
        UpsertFeeTypeCommand: {
            id?: string | null;
            name?: string;
            description?: string;
            active?: boolean;
        };
        BaseResponseOfListOfGroupExamDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["GroupExamDto"][] | null;
        };
        GroupExamDto: {
            id?: string;
            name?: string;
            description?: string;
            iconUrl?: string | null;

            /** Format: int32 */
            order?: number;
            licenseTypeCode?: string | null;
            parentId?: string | null;
            slug?: string;
            type?: components["schemas"]["GroupExamType"] | null;
            children?: components["schemas"]["GroupExamDto"][];
        };
        GetAllGroupExamQuery: Record<string, never>;
        BaseResponseOfListOfLicenseTypeDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["LicenseTypeDto"][] | null;
        };
        BaseResponseOfListOfCitizenCardDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["CitizenCardDto"][] | null;
        };
        CitizenCardDto: {
            id?: string;
            front?: components["schemas"]["FrontCitizenCardDto"] | null;
            back?: components["schemas"]["BackCitizenCardDto"] | null;
            isRecognitionByAi?: boolean;
            isConfirmedByHuman?: boolean;
        };
        FrontCitizenCardDto: {
            fullName?: string;

            /** Format: date */
            birthday?: string;
            gender?: components["schemas"]["GenderType"];
            placeOfOrigin?: components["schemas"]["Address"];
            placeOfResidence?: components["schemas"]["Address"];
            nationality?: string;
            imageUrl?: string | null;
        };

        /** @enum {integer} */
        GenderType: 0 | 1 | 2;
        Address: {
            provinceCode?: string;
            districtCode?: string;
            wardCode?: string;
        };
        BackCitizenCardDto: {

            /** Format: date */
            issuedDate?: string;
            issuedBy?: string;
            imageUrl?: string | null;
        };
        BaseResponseOfCitizenCardPdfResult: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["CitizenCardPdfResult"] | null;
        };
        CitizenCardPdfResult: {
            pdfUrls?: string[];
        };
        CitizenCardPdfRequest: {
            id?: string;
            fullName?: string;

            /** Format: date */
            birthday?: string;
            placeOfOrigin?: string;
            placeOfResidence?: string;
            nationality?: string;

            /** Format: date */
            issuedDate?: string;
            issuedBy?: string;
            imagePath?: string;
        };
        BaseResponseOfQuestionByExamDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["QuestionByExamDto"] | null;
        };
        QuestionByExamDto: {
            examSubmissionId?: string | null;
            examDto?: components["schemas"]["ExamDto"] | null;
            questions?: components["schemas"]["QuestionDto"][];
        };
        QuestionDto: {
            id?: string;

            /** Format: int32 */
            order?: number;
            content?: string;
            imageUrl?: string | null;
            isCriticalQuestion?: boolean;
            answers?: components["schemas"]["AnswerDto"][];
        };
        AnswerDto: {
            id?: string;

            /** Format: int32 */
            order?: number;
            content?: string;
        };
        ChangeQuestionImageUrlCommand: Record<string, never>;
        BaseResponseOfQuestionDetailDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["QuestionDetailDto"] | null;
        };
        QuestionDetailDto: {
            id?: string;

            /** Format: int32 */
            order?: number;
            content?: string;
            imageUrl?: string | null;
            answers?: components["schemas"]["AnswerDto2"][];
            explanation?: string | null;
            isCritical?: boolean;
        };
        AnswerDto2: {
            id?: string;

            /** Format: int32 */
            order?: number;
            isCorrect?: boolean;
            content?: string;
        };
        BaseResponseOfString: components["schemas"]["BaseResponse"] & {
            data?: string | null;
        };
        CreateRegistrationRecordCommand: {
            licenseTypeCode?: string;
            avatarUrl?: string;
            fullname?: string;

            /** Format: date */
            birthday?: string;
            gender?: components["schemas"]["GenderType"];
            phone?: string;
            email?: string | null;
            address?: string | null;
            citizenIdNumber?: string;
            citizenIdFrontImageUrl?: string;
            citizenIdBackImageUrl?: string;

            /** Format: date-time */
            receivedDate?: string;

            /** Format: date-time */
            healthCheckDate?: string | null;
            staffAssigneeId?: string | null;
            collaboratorId?: string | null;
            note?: string | null;
        };
        UpdateRegistrationRecordCommand: {
            id?: string;
            licenseTypeCode?: string;
            avatarUrl?: string;
            fullname?: string;

            /** Format: date */
            birthday?: string;
            gender?: components["schemas"]["GenderType"];
            phone?: string;
            email?: string | null;
            address?: string | null;
            citizenIdNumber?: string;
            citizenIdFrontImageUrl?: string;
            citizenIdBackImageUrl?: string;

            /** Format: date-time */
            receivedDate?: string;

            /** Format: date-time */
            healthCheckDate?: string | null;
            staffAssigneeId?: string | null;
            collaboratorId?: string | null;
            note?: string | null;
        };
        PaginatedListOfGetRegistrationRecordsDto: {
            data?: components["schemas"]["GetRegistrationRecordsDto"][];

            /** Format: int32 */
            pageNumber?: number;

            /** Format: int32 */
            totalPages?: number;

            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        GetRegistrationRecordsDto: {
            id?: string;
            licenseType?: components["schemas"]["GetRegistrationRecordsLicenseTypeDto"];
            fullname?: string;
            phone?: string;

            /** Format: date */
            birthday?: string;
            citizenIdNumber?: string;

            /** Format: date-time */
            receivedDate?: string;

            /** Format: date-time */
            healthCheckDate?: string | null;
            payment?: components["schemas"]["GetRegistrationRecordsPaymentDto"];
            status?: components["schemas"]["RegistrationRecordStatus"];
            staffAssigneeName?: string | null;
            collaboratorName?: string | null;
            note?: string | null;
        };
        GetRegistrationRecordsLicenseTypeDto: {
            code?: string;
            name?: string;
        };
        GetRegistrationRecordsPaymentDto: {

            /** Format: decimal */
            totalAmount?: number;

            /** Format: decimal */
            paidAmount?: number;

            /** Format: decimal */
            remainingAmount?: number;
        };

        /** @enum {integer} */
        RegistrationRecordStatus: 0 | 1 | 2;

        /** @enum {integer} */
        PaymentStatus: 0 | 1 | 2;
        BaseResponseOfUploadFileResult: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["UploadFileResult"] | null;
        };
        UploadFileResult: {
            fileNameOrigin?: string | null;
            fileName?: string | null;
            relativeUrl?: string | null;
        };
        BaseResponseOfListOfUploadFileResult: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["UploadFileResult"][] | null;
        };
        RegisterUserRequest: {
            userName?: string;
            email?: string;
            password?: string;
            avatarUrl?: string;
        };
        BaseResponseOfListOfVehicleTypeDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["VehicleTypeDto"][] | null;
        };
        VehicleTypeDto: {
            code?: string;
            name?: string;
            description?: string;
        };
        GetAllVehicleTypesQuery: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Assignees_GetAssignees: {
        parameters: {
            query?: {
                Search?: string | null;
                AssigneeType?: components["schemas"]["AssigneeType"] | null;
                PageNumber?: number;
                PageSize?: number;
                Active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfAssigneeDto"];
                };
            };
        };
    };
    Assignees_UpsertBrandSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAssigneeCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Assignees_GetAssigneeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfAssigneeDto"];
                };
            };
        };
    };
    Assignees_DeleteAssigneeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Authorization_Exchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Authorization_UserinfoGET: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Authorization_UserinfoPOST: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    BrandSettings_GetBrandSettingByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBrandSettingDto"];
                };
            };
        };
    };
    BrandSettings_GetBrandSettingByOwnerId: {
        parameters: {
            query?: {
                OwnerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBrandSettingDto"];
                };
            };
        };
    };
    BrandSettings_UpsertBrandSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertBrandSettingCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Contacts_CreateContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Exams_GetExamsByGroupExamId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfExamDto"];
                };
            };
        };
    };
    Exams_GenerateExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateExamsCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Exams_GenerationExamFullCritical: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationExamFullCriticalCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Exams_GenerationExamFull: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationExamFullCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Exams_GenerateExam2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRandomExamsCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfExamDto"];
                };
            };
        };
    };
    ExamSubmissions_GetExamSubmissionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfExamSubmissionResultDto"];
                };
            };
        };
    };
    ExamSubmissions_StartExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamSubmissionCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfCreateExamSubmissionResultDto"];
                };
            };
        };
    };
    ExamSubmissions_SubmitExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitExamCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfExamSubmissionResultDto"];
                };
            };
        };
    };
    FeeTypes_GetFeeTypes: {
        parameters: {
            query?: {
                Search?: string | null;
                PageNumber?: number;
                PageSize?: number;
                Active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfFeeTypeDto"];
                };
            };
        };
    };
    FeeTypes_UpsertFeeType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertFeeTypeCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    FeeTypes_GetFeeTypeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfFeeTypeDto"];
                };
            };
        };
    };
    FeeTypes_DeleteFeeTypeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    GroupExams_GetAllGroupExams: {
        parameters: {
            query?: {
                query?: components["schemas"]["GetAllGroupExamQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfGroupExamDto"];
                };
            };
        };
    };
    LicenseTypes_GetAllLicenseTypes: {
        parameters: {
            query?: {
                VehicleTypeCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfLicenseTypeDto"];
                };
            };
        };
    };
    Persons_RecognizeCitizenByFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    formFile?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfCitizenCardDto"];
                };
            };
        };
    };
    Persons_ExportCitizenInfoToPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitizenCardPdfRequest"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfCitizenCardPdfResult"];
                };
            };
        };
    };
    Questions_GetExamsByGroupExamId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfQuestionByExamDto"];
                };
            };
        };
    };
    Questions_ExportCitizenInfoToPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {

                    /** Format: binary */
                    FormFile?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Questions_ChangeQuestionImageUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    command?: components["schemas"]["ChangeQuestionImageUrlCommand"] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Questions_GetQuestionDetailById: {
        parameters: {
            query?: {
                QuestionId?: string;
                ExamId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfQuestionDetailDto"];
                };
            };
        };
    };
    RegistrationRecords_GetRegistrationRecordsWithPagination: {
        parameters: {
            query?: {
                LicenseTypeCode?: string | null;
                PaymentStatus?: components["schemas"]["PaymentStatus"] | null;
                Status?: components["schemas"]["RegistrationRecordStatus"] | null;
                StaffAssigneeId?: string | null;
                CollaboratorId?: string | null;
                Search?: string | null;
                PageNumber?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfGetRegistrationRecordsDto"];
                };
            };
        };
    };
    RegistrationRecords_CreateRegistrationRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegistrationRecordCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    RegistrationRecords_UpdateRegistrationRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRegistrationRecordCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Samples_GetSecretResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Uploads_UploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {

                    /** Format: binary */
                    File?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfUploadFileResult"];
                };
            };
        };
    };
    Uploads_UploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    Files?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfUploadFileResult"];
                };
            };
        };
    };
    Users_GetUserInfoByReferenceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Users_Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    VehicleTypes_GetAllLicenseTypes: {
        parameters: {
            query?: {
                query?: components["schemas"]["GetAllVehicleTypesQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfVehicleTypeDto"];
                };
            };
        };
    };
}
