/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exam/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Exam_GetExamAddressesWithPaginationQuery"];
        put?: never;
        post: operations["Exam_CreateExamAddressCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Exam_GetExamSchedulesWithPaginationQuery"];
        put: operations["Exam_UpdateExamScheduleCommand"];
        post: operations["Exam_CreateExamScheduleCommand"];
        delete: operations["Exam_DeleteExamScheduleCommand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Exam_GetExamScheduleByIdQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/schedules/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Exam_UpdateResultsForExamScheduleCommand"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/schedules/registrations/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Exam_SetExamScheduleForBulkLicenseRegistrationsCommand"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/schedules/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Exam_SetExamScheduleForLicenseRegistrationCommand"];
        post?: never;
        delete: operations["Exam_RemoveExamScheduleForLicenseRegistrationCommand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/licenses/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Licenses_GetLicenseRegistrationsWithPaginationQuery"];
        put: operations["Licenses_UpdateLicenseRegistrationCommand"];
        post: operations["Licenses_CreateLicenseRegistrationCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/licenses/registrations/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Licenses_CreateLicenseRegistrationForCustomizeCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/licenses/registrations/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Licenses_ApproveLicenseRegistrationCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/licenses/registrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Licenses_GetLicenseRegistrationByIdQuery"];
        put?: never;
        post?: never;
        delete: operations["Licenses_DeleteLicenseRegistrationCommand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/licenses/registrations/paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Licenses_GetLicenseRegistrationsHasPaidForAllWithPaginationQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Statistics_GetStatisticOverviewByTimeRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/exam-pass-fail-percentage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Statistics_GetExamPassFailPercentageByTimeRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/vehicle-type-percentage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Statistics_GetVehicleTypePercentageByTimeRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/vehicle-type-quantity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Statistics_GetVehicleTypeQuantityByTimeRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Uploads_UploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Uploads_UploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Authorization_Exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/recognition/citizen-by-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Persons_RecognizeCitizenByFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Persons_ExportCitizenInfoToPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Samples_GetSecretResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_GetUserInfoByReferenceToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Users_Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedListOfExamAddressVm: {
            data?: components["schemas"]["ExamAddressVm"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        ExamAddressVm: {
            id?: string;
            fullAddress?: string;
        };
        PaginatedListOfExamScheduleVm: {
            data?: components["schemas"]["ExamScheduleVm"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        ExamScheduleVm: {
            id?: string;
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            note?: string;
            limitType?: components["schemas"]["LimitType"];
            /** Format: int32 */
            registrationLimit?: number | null;
            /** Format: int32 */
            registeredStudents?: number;
            /** Format: int32 */
            passedStudents?: number | null;
            examAddress?: components["schemas"]["ExamAddressVm"];
        };
        /** @enum {integer} */
        LimitType: 0 | 1;
        BaseResponseOfExamScheduleById: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["ExamScheduleById"] | null;
        };
        ExamScheduleById: {
            id?: string;
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            note?: string;
            limitType?: components["schemas"]["LimitType"];
            /** Format: int32 */
            registrationLimit?: number | null;
            /** Format: int32 */
            registeredStudents?: number;
            /** Format: int32 */
            passedStudents?: number | null;
            examAddress?: components["schemas"]["ExamAddressVm"];
        };
        BaseResponse: {
            success?: boolean;
            message?: string | null;
            statusCode?: components["schemas"]["HttpStatusCode"];
        };
        /** @enum {integer} */
        HttpStatusCode: 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 226 | 300 | 300 | 301 | 301 | 302 | 302 | 303 | 303 | 304 | 305 | 306 | 307 | 307 | 308 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 421 | 422 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 510 | 511;
        BaseResponseOfString: components["schemas"]["BaseResponse"] & {
            data?: string | null;
        };
        CreateExamScheduleCommand: {
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            limitType?: components["schemas"]["LimitType"];
            /** Format: int32 */
            registrationLimit?: number | null;
            note?: string;
            examAddressId?: string;
        };
        UpdateExamScheduleCommand: {
            id?: string;
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            limitType?: components["schemas"]["LimitType"];
            /** Format: int32 */
            registrationLimit?: number | null;
            note?: string;
            examAddressId?: string;
        };
        DeleteExamScheduleCommand: {
            id?: string;
        };
        UpdateResultsForExamScheduleCommand: {
            id?: string;
            results?: components["schemas"]["UpdateLicenseRegistrationResults"][];
        };
        UpdateLicenseRegistrationResults: {
            licenseRegistrationId?: string;
            passed?: boolean;
        };
        SetExamScheduleForBulkLicenseRegistrationsCommand: {
            examScheduleId?: string;
            licenseRegistrationIds?: string[];
        };
        SetExamScheduleForLicenseRegistrationCommand: {
            examScheduleId?: string;
            licenseRegistrationId?: string;
        };
        RemoveExamScheduleForLicenseRegistrationCommand: {
            examScheduleId?: string;
            licenseRegistrationId?: string;
        };
        PaginatedListOfLicenseRegistrationVm: {
            data?: components["schemas"]["LicenseRegistrationVm"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        LicenseRegistrationVm: {
            id?: string;
            vehicleType?: components["schemas"]["VehicleType"];
            licenseType?: components["schemas"]["LicenseType"];
            hasCarLicense?: boolean;
            hasCompletedHealthCheck?: boolean;
            hasApproved?: boolean;
            person?: components["schemas"]["PersonVm"];
            note?: string;
            isPaid?: boolean;
            /** Format: decimal */
            amount?: number;
            isRetake?: boolean;
            examScheduleId?: string | null;
            passed?: boolean | null;
            status?: components["schemas"]["LicenseRegistrationStatus"];
        };
        /** @enum {integer} */
        VehicleType: 0 | 1;
        /** @enum {integer} */
        LicenseType: 0 | 1 | 2 | 3;
        PersonVm: {
            id?: string;
            avatarUrl?: string;
            fullName?: string;
            /** Format: date */
            birthday?: string;
            sex?: components["schemas"]["SexType"];
            phoneNumber?: string;
            email?: string;
            address?: components["schemas"]["PersonAddressVm"];
            citizenCardId?: string;
            citizenCardFrontImgUrl?: string;
            citizenCardBackImgUrl?: string;
            /** Format: date */
            citizenCardDateOfIssue?: string;
            citizenCardPlaceOfIssue?: string;
        };
        /** @enum {integer} */
        SexType: 0 | 1 | 2;
        PersonAddressVm: {
            provinceCode?: string;
            districtCode?: string;
            wardCode?: string;
            addressDetail?: string;
        };
        /** @enum {integer} */
        LicenseRegistrationStatus: 0 | 1 | 2 | 3;
        CreateLicenseRegistrationCommand: {
            vehicleType?: components["schemas"]["VehicleType"];
            licenseType?: components["schemas"]["LicenseType"];
            hasCarLicense?: boolean;
            hasCompletedHealthCheck?: boolean;
            hasApproved?: boolean;
            ownerId?: string | null;
            person?: components["schemas"]["PersonCommand"];
            note?: string;
            isPaid?: boolean;
            /** Format: decimal */
            amount?: number;
        };
        PersonCommand: {
            avatarUrl?: string;
            fullName?: string;
            /** Format: date */
            birthday?: string;
            sex?: components["schemas"]["SexType"];
            phoneNumber?: string;
            email?: string;
            address?: components["schemas"]["AddressCommand"];
            citizenCardId?: string;
            citizenCardFrontImgUrl?: string;
            citizenCardBackImgUrl?: string;
            /** Format: date */
            citizenCardDateOfIssue?: string;
            citizenCardPlaceOfIssue?: string;
        };
        AddressCommand: {
            provinceCode?: string;
            districtCode?: string;
            wardCode?: string;
            addressDetail?: string;
        };
        BaseResponseOfBoolean: components["schemas"]["BaseResponse"] & {
            data?: boolean;
        };
        ApproveLicenseRegistrationCommand: {
            id?: string;
        };
        UpdateLicenseRegistrationCommand: {
            id?: string;
            vehicleType?: components["schemas"]["VehicleType"];
            licenseType?: components["schemas"]["LicenseType"];
            hasCarLicense?: boolean;
            hasCompletedHealthCheck?: boolean;
            hasApproved?: boolean;
            person?: components["schemas"]["PersonCommand2"];
            note?: string;
            isPaid?: boolean;
            /** Format: decimal */
            amount?: number;
        };
        PersonCommand2: {
            avatarUrl?: string;
            fullName?: string;
            /** Format: date */
            birthday?: string;
            sex?: components["schemas"]["SexType"];
            phoneNumber?: string;
            email?: string;
            address?: components["schemas"]["AddressCommand2"];
            citizenCardId?: string;
            citizenCardFrontImgUrl?: string;
            citizenCardBackImgUrl?: string;
        };
        AddressCommand2: {
            provinceCode?: string;
            districtCode?: string;
            wardCode?: string;
            addressDetail?: string;
        };
        BaseResponseOfLicenseRegistrationById: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["LicenseRegistrationById"] | null;
        };
        LicenseRegistrationById: {
            id?: string;
            vehicleType?: components["schemas"]["VehicleType"];
            licenseType?: components["schemas"]["LicenseType"];
            hasCarLicense?: boolean;
            hasCompletedHealthCheck?: boolean;
            hasApproved?: boolean;
            person?: components["schemas"]["PersonById"];
            note?: string;
            isPaid?: boolean;
            /** Format: decimal */
            amount?: number;
            isRetake?: boolean;
            examScheduleId?: string | null;
            passed?: boolean | null;
            status?: components["schemas"]["LicenseRegistrationStatus"];
        };
        PersonById: {
            id?: string;
            avatarUrl?: string;
            fullName?: string;
            /** Format: date */
            birthday?: string;
            sex?: components["schemas"]["SexType"];
            phoneNumber?: string;
            email?: string;
            address?: components["schemas"]["PersonAddressById"];
            citizenCardId?: string;
            citizenCardFrontImgUrl?: string;
            citizenCardBackImgUrl?: string;
        };
        PersonAddressById: {
            provinceCode?: string;
            districtCode?: string;
            wardCode?: string;
            addressDetail?: string;
        };
        PaginatedListOfLicenseRegistrationHasPaidForAllVm: {
            data?: components["schemas"]["LicenseRegistrationHasPaidForAllVm"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            totalCount?: number;
            hasPreviousPage?: boolean;
            hasNextPage?: boolean;
        };
        LicenseRegistrationHasPaidForAllVm: {
            id?: string;
            licenseType?: components["schemas"]["LicenseType"];
            person?: components["schemas"]["PersonHasPaidForAllVm"];
            note?: string;
            examRegistration?: components["schemas"]["ExamRegistrationHasPaidForAllVm"];
        };
        PersonHasPaidForAllVm: {
            id?: string;
            avatarUrl?: string;
            fullName?: string;
            /** Format: date */
            birthday?: string;
            sex?: components["schemas"]["SexType"];
            phoneNumber?: string;
            email?: string;
            citizenCardId?: string;
        };
        ExamRegistrationHasPaidForAllVm: {
            id?: string;
            isRetake?: boolean;
            examSchedule?: components["schemas"]["ExamScheduleHasPaidForAllVm"] | null;
        };
        ExamScheduleHasPaidForAllVm: {
            id?: string;
            name?: string;
            /** Format: date-time */
            dateTime?: string;
        };
        BaseResponseOfGetStatisticOverviewByTimeRangeResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["GetStatisticOverviewByTimeRangeResponse"] | null;
        };
        GetStatisticOverviewByTimeRangeResponse: {
            /** Format: int32 */
            totalLicenseRegistration?: number;
            /** Format: float */
            increasePercentageLicenseRegistration?: number;
            /** Format: int32 */
            totalMotorbike?: number;
            /** Format: float */
            increasePercentageMotorbike?: number;
            /** Format: int32 */
            totalCar?: number;
            /** Format: float */
            increasePercentageCar?: number;
            /** Format: int64 */
            totalRevenue?: number;
            /** Format: float */
            increasePercentageRevenue?: number;
            /** Format: int32 */
            totalPaid?: number;
            /** Format: float */
            percentagePaid?: number;
            /** Format: float */
            percentageUnpaid?: number;
        };
        BaseResponseOfGetExamPassFailPercentageByTimeRangeResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["GetExamPassFailPercentageByTimeRangeResponse"] | null;
        };
        GetExamPassFailPercentageByTimeRangeResponse: {
            dataFollowExamSchedule?: components["schemas"]["DataFollowExamScheduleResponse"][] | null;
            dataFollowMonth?: components["schemas"]["DataFollowMonthResponse"][] | null;
        };
        DataFollowExamScheduleResponse: {
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            /** Format: float */
            passPercentage?: number;
            /** Format: float */
            failPercentage?: number;
        };
        DataFollowMonthResponse: {
            monthOfYear?: components["schemas"]["MonthOfYearType"];
            /** Format: float */
            passPercentage?: number;
            /** Format: float */
            failPercentage?: number;
        };
        /** @enum {integer} */
        MonthOfYearType: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
        BaseResponseOfGetVehicleTypePercentageByTimeRangeResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["GetVehicleTypePercentageByTimeRangeResponse"] | null;
        };
        GetVehicleTypePercentageByTimeRangeResponse: {
            dataFollowExamSchedule?: components["schemas"]["DataFollowExamScheduleResponse2"][] | null;
            dataFollowMonth?: components["schemas"]["DataFollowMonthResponse2"][] | null;
        };
        DataFollowExamScheduleResponse2: {
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            /** Format: float */
            motorbikePercentage?: number;
            /** Format: float */
            carPercentage?: number;
        };
        DataFollowMonthResponse2: {
            monthOfYear?: components["schemas"]["MonthOfYearType"];
            /** Format: float */
            motorbikePercentage?: number;
            /** Format: float */
            carPercentage?: number;
        };
        BaseResponseOfGetVehicleTypeQuantityByTimeRangeResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["GetVehicleTypeQuantityByTimeRangeResponse"] | null;
        };
        GetVehicleTypeQuantityByTimeRangeResponse: {
            dataFollowExamSchedule?: components["schemas"]["DataFollowExamScheduleResponse3"][] | null;
            dataFollowMonth?: components["schemas"]["DataFollowMonthResponse3"][] | null;
        };
        DataFollowExamScheduleResponse3: {
            name?: string;
            /** Format: date-time */
            dateTime?: string;
            /** Format: int32 */
            motorbikeQuantity?: number;
            /** Format: int32 */
            carQuantity?: number;
        };
        DataFollowMonthResponse3: {
            monthOfYear?: components["schemas"]["MonthOfYearType"];
            /** Format: int32 */
            motorbikeQuantity?: number;
            /** Format: int32 */
            carQuantity?: number;
        };
        BaseResponseOfUploadFileResult: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["UploadFileResult"] | null;
        };
        UploadFileResult: {
            fileNameOrigin?: string | null;
            fileName?: string | null;
            relativeUrl?: string | null;
        };
        BaseResponseOfListOfUploadFileResult: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["UploadFileResult"][] | null;
        };
        BaseResponseOfListOfCitizenCardDto: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["CitizenCardDto"][] | null;
        };
        CitizenCardDto: {
            id?: string;
            front?: components["schemas"]["FrontCitizenCardDto"] | null;
            back?: components["schemas"]["BackCitizenCardDto"] | null;
            isRecognitionByAi?: boolean;
            isConfirmedByHuman?: boolean;
        };
        FrontCitizenCardDto: {
            fullName?: string;
            /** Format: date */
            birthday?: string;
            sex?: components["schemas"]["SexType"];
            placeOfOrigin?: components["schemas"]["Address"];
            placeOfResidence?: components["schemas"]["Address"];
            nationality?: string;
            imageUrl?: string | null;
        };
        Address: {
            provinceCode?: string;
            districtCode?: string;
            wardCode?: string;
        };
        BackCitizenCardDto: {
            /** Format: date */
            issuedDate?: string;
            issuedBy?: string;
            imageUrl?: string | null;
        };
        BaseResponseOfCitizenCardPdfResult: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["CitizenCardPdfResult"] | null;
        };
        CitizenCardPdfResult: {
            pdfUrls?: string[];
        };
        CitizenCardPdfRequest: {
            id?: string;
            fullName?: string;
            /** Format: date */
            birthday?: string;
            placeOfOrigin?: string;
            placeOfResidence?: string;
            nationality?: string;
            /** Format: date */
            issuedDate?: string;
            issuedBy?: string;
            imagePath?: string;
        };
        RegisterUserRequest: {
            userName?: string;
            email?: string;
            password?: string;
            avatarUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Exam_GetExamAddressesWithPaginationQuery: {
        parameters: {
            query?: {
                PageNumber?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfExamAddressVm"];
                };
            };
        };
    };
    Exam_CreateExamAddressCommand: {
        parameters: {
            query?: {
                FullAddress?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    Exam_GetExamSchedulesWithPaginationQuery: {
        parameters: {
            query?: {
                PageNumber?: number;
                PageSize?: number;
                Search?: string | null;
                HasAvailableSlots?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfExamScheduleVm"];
                };
            };
        };
    };
    Exam_UpdateExamScheduleCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExamScheduleCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Exam_CreateExamScheduleCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamScheduleCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Exam_DeleteExamScheduleCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteExamScheduleCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Exam_GetExamScheduleByIdQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfExamScheduleById"];
                };
            };
        };
    };
    Exam_UpdateResultsForExamScheduleCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResultsForExamScheduleCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Exam_SetExamScheduleForBulkLicenseRegistrationsCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetExamScheduleForBulkLicenseRegistrationsCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Exam_SetExamScheduleForLicenseRegistrationCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetExamScheduleForLicenseRegistrationCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Exam_RemoveExamScheduleForLicenseRegistrationCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveExamScheduleForLicenseRegistrationCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Licenses_GetLicenseRegistrationsWithPaginationQuery: {
        parameters: {
            query?: {
                PageNumber?: number;
                PageSize?: number;
                Search?: string | null;
                ExamScheduleId?: string | null;
                IsPaid?: boolean | null;
                IsExamScheduled?: boolean | null;
                HasCompletedHealthCheck?: boolean[] | null;
                HasApproved?: boolean[] | null;
                LicenseType?: components["schemas"]["LicenseType"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfLicenseRegistrationVm"];
                };
            };
        };
    };
    Licenses_UpdateLicenseRegistrationCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLicenseRegistrationCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Licenses_CreateLicenseRegistrationCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLicenseRegistrationCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Licenses_CreateLicenseRegistrationForCustomizeCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLicenseRegistrationCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Licenses_ApproveLicenseRegistrationCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveLicenseRegistrationCommand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfBoolean"];
                };
            };
        };
    };
    Licenses_GetLicenseRegistrationByIdQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfLicenseRegistrationById"];
                };
            };
        };
    };
    Licenses_DeleteLicenseRegistrationCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfString"];
                };
            };
        };
    };
    Licenses_GetLicenseRegistrationsHasPaidForAllWithPaginationQuery: {
        parameters: {
            query?: {
                PageNumber?: number;
                PageSize?: number;
                Search?: string;
                ExamScheduleId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListOfLicenseRegistrationHasPaidForAllVm"];
                };
            };
        };
    };
    Statistics_GetStatisticOverviewByTimeRange: {
        parameters: {
            query?: {
                StartDate?: string;
                EndDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfGetStatisticOverviewByTimeRangeResponse"];
                };
            };
        };
    };
    Statistics_GetExamPassFailPercentageByTimeRange: {
        parameters: {
            query?: {
                StartDate?: string;
                EndDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfGetExamPassFailPercentageByTimeRangeResponse"];
                };
            };
        };
    };
    Statistics_GetVehicleTypePercentageByTimeRange: {
        parameters: {
            query?: {
                StartDate?: string;
                EndDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfGetVehicleTypePercentageByTimeRangeResponse"];
                };
            };
        };
    };
    Statistics_GetVehicleTypeQuantityByTimeRange: {
        parameters: {
            query?: {
                StartDate?: string;
                EndDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfGetVehicleTypeQuantityByTimeRangeResponse"];
                };
            };
        };
    };
    Uploads_UploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    File?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfUploadFileResult"];
                };
            };
        };
    };
    Uploads_UploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    Files?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfUploadFileResult"];
                };
            };
        };
    };
    Authorization_Exchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Persons_RecognizeCitizenByFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    formFile?: string[] | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfListOfCitizenCardDto"];
                };
            };
        };
    };
    Persons_ExportCitizenInfoToPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitizenCardPdfRequest"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseOfCitizenCardPdfResult"];
                };
            };
        };
    };
    Samples_GetSecretResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Users_GetUserInfoByReferenceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    Users_Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
}
